name: Daily Shipping Schedule Scraper

on:
  schedule:
    # 6:13 AM SL Time (Off-peak highly reliable time)
    - cron: '43 0 * * *'  
  workflow_dispatch:      # Allows you to run it manually right away

jobs:
  scrape-shipping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run shipping scraper
        # Executes the script in the new folder path
        run: python Data/Shipping/shipping_scraper.py

      - name: Commit and Push JSON
        run: |
          git config --global user.name "GitHub-Actions-Bot"
          git config --global user.email "actions@github.com"
          # Commits the JSON file from the new folder path
          git add Data/Shipping/shipping_schedule.json
          git commit -m "Automated update: Japan to Hambantota shipping schedule" || exit 0
          git push
